"""Prime-owned exact number-theory capabilities."""

from jacobian.contracts.number_theory import (
    BooleanResult,
    IntegerValueRequest,
    IntegerValueResult,
    NonnegativeIntegerRequest,
    PositiveIntegerRequest,
)
from jacobian.domains.number_theory._support import (
    number_theory_operation,
)
from jacobian.domains.number_theory.operations import (
    compute_euler_totient,
    compute_mobius,
    compute_next_prime,
    compute_nth_prime,
    compute_previous_prime,
    compute_prime_count,
    compute_primorial,
    decide_prime,
)

PRIME_CAPABILITIES = (
    number_theory_operation(
        "integer.decide.prime",
        "Decide integer primality",
        "Decide whether one integer is prime.",
        IntegerValueRequest,
        BooleanResult,
        decide_prime,
        "number-theory",
        "predicate",
    ),
    number_theory_operation(
        "integer.compute.next_prime",
        "Compute next prime",
        "Compute the least prime strictly greater than n.",
        NonnegativeIntegerRequest,
        IntegerValueResult,
        compute_next_prime,
        "number-theory",
        "prime",
    ),
    number_theory_operation(
        "integer.compute.previous_prime",
        "Compute previous prime",
        "Compute the greatest prime strictly below n.",
        NonnegativeIntegerRequest,
        IntegerValueResult,
        compute_previous_prime,
        "number-theory",
        "prime",
    ),
    number_theory_operation(
        "integer.compute.prime_count",
        "Count primes through n",
        "Count primes not exceeding one nonnegative integer.",
        NonnegativeIntegerRequest,
        IntegerValueResult,
        compute_prime_count,
        "number-theory",
        "prime",
    ),
    number_theory_operation(
        "integer.compute.nth_prime",
        "Compute nth prime",
        "Compute the nth prime using one-based indexing.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_nth_prime,
        "number-theory",
        "prime",
    ),
    number_theory_operation(
        "integer.compute.primorial",
        "Compute primorial",
        "Compute the product of the first n primes.",
        NonnegativeIntegerRequest,
        IntegerValueResult,
        compute_primorial,
        "number-theory",
        "prime",
    ),
    number_theory_operation(
        "integer.compute.euler_totient",
        "Compute Euler totient",
        "Count residues coprime to one positive integer.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_euler_totient,
        "number-theory",
        "arithmetic-function",
    ),
    number_theory_operation(
        "integer.compute.mobius",
        "Compute Mobius value",
        "Compute the Mobius arithmetic function of one positive integer.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_mobius,
        "number-theory",
        "arithmetic-function",
    ),
)
