"""Sequence aggregate capabilities over finite integer sequences."""

from jacobian.contracts.sequences import (
    IntegerSequenceRequest,
    IntegerSequenceValueResult,
)
from jacobian.domains.sequences._support import sequence_operation
from jacobian.domains.sequences.operations import (
    sequence_distinct_count,
    sequence_gcd,
    sequence_lcm,
    sequence_maximum,
    sequence_minimum,
    sequence_product,
    sequence_range,
    sequence_sum,
)

SEQUENCE_AGGREGATE_CAPABILITIES = (
    sequence_operation(
        "sequence.compute.sum",
        "Sum integer sequence",
        "Compute the exact sum of a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_sum,
        "sequence",
        "exact",
    ),
    sequence_operation(
        "sequence.compute.product",
        "Multiply integer sequence",
        "Compute the exact product of a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_product,
        "sequence",
        "exact",
    ),
    sequence_operation(
        "sequence.compute.gcd",
        "Compute sequence gcd",
        "Compute the gcd of every value in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_gcd,
        "sequence",
        "divisibility",
    ),
    sequence_operation(
        "sequence.compute.lcm",
        "Compute sequence lcm",
        "Compute the lcm of every value in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_lcm,
        "sequence",
        "divisibility",
    ),
    sequence_operation(
        "sequence.compute.minimum",
        "Compute sequence minimum",
        "Compute the least value in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_minimum,
        "sequence",
        "order",
    ),
    sequence_operation(
        "sequence.compute.maximum",
        "Compute sequence maximum",
        "Compute the greatest value in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_maximum,
        "sequence",
        "order",
    ),
    sequence_operation(
        "sequence.compute.range",
        "Compute sequence range",
        "Compute maximum minus minimum for a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_range,
        "sequence",
        "statistic",
    ),
    sequence_operation(
        "sequence.compute.distinct_count",
        "Count distinct sequence values",
        "Count distinct values in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceValueResult,
        sequence_distinct_count,
        "sequence",
        "counting",
    ),
)
