"""Sequence transform capabilities over finite integer sequences."""

from jacobian.contracts.sequences import (
    IntegerSequenceListResult,
    IntegerSequenceRequest,
)
from jacobian.domains._examples import example
from jacobian.domains.sequences._support import sequence_operation
from jacobian.domains.sequences.operations import (
    first_differences,
    parities,
    prefix_gcds,
    prefix_lcms,
    prefix_maxima,
    prefix_minima,
    prefix_products,
    prefix_sums,
    reverse_sequence,
    second_differences,
    signs,
    sort_sequence,
    sorted_unique,
)

SEQUENCE_TRANSFORM_CAPABILITIES = (
    sequence_operation(
        "sequence.compute.prefix_sums",
        "Compute prefix sums",
        "Compute every nonempty prefix sum of a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_sums,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.compute.first_differences",
        "Compute first differences",
        "Compute adjacent first differences of a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        first_differences,
        "sequence",
        "transform",
        invocation_examples=(
            example(
                "square_first_differences",
                "Compute differences of consecutive squares.",
                {"values": ["1", "4", "9", "16"]},
            ),
        ),
    ),
    sequence_operation(
        "sequence.compute.prefix_products",
        "Compute prefix products",
        "Compute every nonempty prefix product of a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_products,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.compute.prefix_minima",
        "Compute prefix minima",
        "Compute the minimum of every nonempty prefix.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_minima,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.compute.prefix_maxima",
        "Compute prefix maxima",
        "Compute the maximum of every nonempty prefix.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_maxima,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.compute.prefix_gcds",
        "Compute prefix gcds",
        "Compute the gcd of every nonempty prefix.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_gcds,
        "sequence",
        "divisibility",
        invocation_examples=(
            example(
                "prefix_gcds_18_24_15",
                "Compute prefix gcds of 18, 24, and 15.",
                {"values": ["18", "24", "15"]},
            ),
        ),
    ),
    sequence_operation(
        "sequence.compute.prefix_lcms",
        "Compute prefix lcms",
        "Compute the lcm of every nonempty prefix.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        prefix_lcms,
        "sequence",
        "divisibility",
    ),
    sequence_operation(
        "sequence.compute.second_differences",
        "Compute second differences",
        "Compute adjacent differences of the first-difference sequence.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        second_differences,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.transform.sorted_unique",
        "Sort and deduplicate sequence",
        "Return the strictly increasing values occurring in a finite integer sequence.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        sorted_unique,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.transform.sort",
        "Sort integer sequence",
        "Return a nondecreasing ordering retaining multiplicities.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        sort_sequence,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.transform.reverse",
        "Reverse integer sequence",
        "Return the finite integer sequence in reverse order.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        reverse_sequence,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.transform.parities",
        "Compute parity sequence",
        "Return 0 for even and 1 for odd at each position.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        parities,
        "sequence",
        "transform",
    ),
    sequence_operation(
        "sequence.transform.signs",
        "Compute sign sequence",
        "Return -1, 0, or 1 for each sequence value.",
        IntegerSequenceRequest,
        IntegerSequenceListResult,
        signs,
        "sequence",
        "transform",
    ),
)
