"""Rational-owned exact arithmetic capabilities.

The arithmetic domain owns rational arithmetic (reciprocal, negation,
absolute value, sum, difference, product, quotient), rational order
(minimum, maximum), rational rounding (floor, ceiling), rational
representation (continued fraction), and rational predicates (equality,
strict less-than).
"""

from jacobian.contracts.rationals import (
    RationalComparisonResult,
    RationalContinuedFractionResult,
    RationalIntegerResult,
    RationalPairRequest,
    RationalValueRequest,
    RationalValueResult,
)
from jacobian.domains._examples import example
from jacobian.domains.arithmetic._support import arithmetic_operation
from jacobian.domains.arithmetic.operations import (
    ceiling,
    continued_fraction,
    difference,
    equal,
    floor,
    less_than,
    maximum,
    minimum,
    negation,
    product,
    quotient,
    rational_absolute_value,
    reciprocal,
    sum_rationals,
)

RATIONAL_CAPABILITIES = (
    arithmetic_operation(
        "rational.compute.reciprocal",
        "Compute rational reciprocal",
        "Compute the reduced reciprocal of one nonzero rational.",
        RationalValueRequest,
        RationalValueResult,
        reciprocal,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.negation",
        "Negate rational",
        "Compute the exact additive inverse of one rational.",
        RationalValueRequest,
        RationalValueResult,
        negation,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.absolute_value",
        "Compute rational absolute value",
        "Compute the exact absolute value of one rational.",
        RationalValueRequest,
        RationalValueResult,
        rational_absolute_value,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.sum",
        "Add rationals",
        "Compute the reduced sum of two rationals.",
        RationalPairRequest,
        RationalValueResult,
        sum_rationals,
        "rational",
        "exact",
        invocation_examples=(example("one_half_plus_one_third", "Add one half and one third.", {"left": {"num": "1", "den": "2"}, "right": {"num": "1", "den": "3"}}),),
    ),
    arithmetic_operation(
        "rational.compute.difference",
        "Subtract rationals",
        "Compute the reduced difference of two rationals.",
        RationalPairRequest,
        RationalValueResult,
        difference,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.product",
        "Multiply rationals",
        "Compute the reduced product of two rationals.",
        RationalPairRequest,
        RationalValueResult,
        product,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.quotient",
        "Divide rationals",
        "Compute the reduced quotient of two rationals.",
        RationalPairRequest,
        RationalValueResult,
        quotient,
        "rational",
        "exact",
    ),
    arithmetic_operation(
        "rational.compute.minimum",
        "Compute rational minimum",
        "Return the lesser of two exact rationals.",
        RationalPairRequest,
        RationalValueResult,
        minimum,
        "rational",
        "order",
    ),
    arithmetic_operation(
        "rational.compute.maximum",
        "Compute rational maximum",
        "Return the greater of two exact rationals.",
        RationalPairRequest,
        RationalValueResult,
        maximum,
        "rational",
        "order",
    ),
    arithmetic_operation(
        "rational.compute.floor",
        "Floor rational",
        "Compute the greatest integer not exceeding one rational.",
        RationalValueRequest,
        RationalIntegerResult,
        floor,
        "rational",
        "rounding",
    ),
    arithmetic_operation(
        "rational.compute.ceiling",
        "Ceil rational",
        "Compute the least integer not below one rational.",
        RationalValueRequest,
        RationalIntegerResult,
        ceiling,
        "rational",
        "rounding",
    ),
    arithmetic_operation(
        "rational.compute.continued_fraction",
        "Expand rational continued fraction",
        "Compute the finite simple continued fraction of one rational.",
        RationalValueRequest,
        RationalContinuedFractionResult,
        continued_fraction,
        "rational",
        "representation",
        invocation_examples=(example("negative_seven_fifths", "Expand negative seven fifths as a continued fraction.", {"value": {"num": "-7", "den": "5"}}),),
    ),
    arithmetic_operation(
        "rational.decide.equal",
        "Decide rational equality",
        "Decide exact equality of two reduced rationals.",
        RationalPairRequest,
        RationalComparisonResult,
        equal,
        "rational",
        "predicate",
    ),
    arithmetic_operation(
        "rational.decide.less_than",
        "Compare rationals",
        "Decide whether the first rational is strictly less than the second.",
        RationalPairRequest,
        RationalComparisonResult,
        less_than,
        "rational",
        "predicate",
    ),
)
