"""Counting-owned exact combinatorics capabilities."""

from jacobian.contracts.combinatorics import (
    IntegerListRequest,
    IntegerResult,
    NonnegativeIntegerRequest,
    NonnegativePairRequest,
)
from jacobian.domains._examples import example
from jacobian.domains.combinatorics._support import (
    combinatorics_operation,
)
from jacobian.domains.combinatorics.operations import (
    binomial,
    catalan,
    central_binomial,
    compositions,
    derangements,
    double_factorial,
    factorial,
    motzkin,
    multinomial,
    permutations,
)

COUNTING_CAPABILITIES = (
    combinatorics_operation(
        "combinatorics.compute.factorial",
        "Compute factorial",
        "Compute n factorial exactly.",
        NonnegativeIntegerRequest,
        IntegerResult,
        factorial,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.double_factorial",
        "Compute double factorial",
        "Compute n double factorial exactly.",
        NonnegativeIntegerRequest,
        IntegerResult,
        double_factorial,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.derangements",
        "Count derangements",
        "Count fixed-point-free permutations of n labeled objects.",
        NonnegativeIntegerRequest,
        IntegerResult,
        derangements,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.binomial",
        "Compute binomial coefficient",
        "Count k-element subsets of an n-element set.",
        NonnegativePairRequest,
        IntegerResult,
        binomial,
        "combinatorics",
        "counting",
        invocation_examples=(
            example("binomial_5_choose_2", "Compute 5 choose 2.", {"n": 5, "k": 2}),
        ),
    ),
    combinatorics_operation(
        "combinatorics.compute.multinomial",
        "Compute multinomial coefficient",
        "Count arrangements with the supplied nonnegative part sizes.",
        IntegerListRequest,
        IntegerResult,
        multinomial,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.permutations",
        "Count partial permutations",
        "Count ordered selections of k objects from n.",
        NonnegativePairRequest,
        IntegerResult,
        permutations,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.catalan",
        "Compute Catalan number",
        "Compute the nth Catalan number.",
        NonnegativeIntegerRequest,
        IntegerResult,
        catalan,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.motzkin",
        "Compute Motzkin number",
        "Compute the nth Motzkin path count.",
        NonnegativeIntegerRequest,
        IntegerResult,
        motzkin,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.central_binomial",
        "Compute central binomial coefficient",
        "Compute binomial(2n,n) exactly.",
        NonnegativeIntegerRequest,
        IntegerResult,
        central_binomial,
        "combinatorics",
        "counting",
    ),
    combinatorics_operation(
        "combinatorics.compute.compositions",
        "Count positive compositions",
        "Count ordered positive-part compositions of n into k parts.",
        NonnegativePairRequest,
        IntegerResult,
        compositions,
        "combinatorics",
        "counting",
    ),
)
